CREATE TYPE "user_type" AS ENUM ('admin', 'doctor', 'patient');
CREATE TYPE "gender" AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
CREATE TYPE "doctor_specialization" AS ENUM ('cardiology', 'dermatology', 'endocrinology', 'ent', 'family_medicine', 'gastroenterology', 'general_medicine', 'gynecology', 'neurology', 'oncology', 'ophthalmology', 'orthopedics', 'pediatrics', 'psychiatry', 'radiology', 'urology', 'other');
CREATE TYPE "blood_group" AS ENUM ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');
CREATE TYPE "allergy_severity" AS ENUM ('mild', 'moderate', 'severe');
CREATE TYPE "chronic_condition_status" AS ENUM ('active', 'inactive', 'resolved');
CREATE TYPE "medical_record_type" AS ENUM ('prescription', 'report', 'scan', 'vaccination', 'other');
CREATE TYPE "medical_record_privacy" AS ENUM ('private', 'shared');
CREATE TYPE "reminder_type" AS ENUM ('medicine', 'checkup', 'vaccination', 'custom');
CREATE TYPE "reminder_frequency" AS ENUM ('once', 'daily', 'weekly', 'monthly');
CREATE TYPE "reminder_status" AS ENUM ('pending', 'completed', 'missed');
CREATE TYPE "share_token_scope" AS ENUM ('prescriptions', 'reports', 'vaccinations', 'all');
CREATE TYPE "share_token_status" AS ENUM ('active', 'revoked', 'expired');
CREATE TYPE "audit_log_action" AS ENUM ('view', 'download', 'print', 'share');
CREATE TYPE "audit_log_status" AS ENUM ('success', 'failed');
CREATE TYPE "emergency_sos_status" AS ENUM ('active', 'resolved', 'cancelled');
CREATE TYPE "emergency_contact_relationship" AS ENUM ('spouse', 'parent', 'sibling', 'child', 'relative', 'friend', 'caregiver', 'other');

ALTER TABLE "users" ALTER COLUMN "type" TYPE "user_type" USING "type"::"user_type";
ALTER TABLE "users" ALTER COLUMN "gender" TYPE "gender" USING "gender"::"gender";
ALTER TABLE "doctors" ALTER COLUMN "specialization" TYPE "doctor_specialization" USING "specialization"::"doctor_specialization";
ALTER TABLE "patients" ALTER COLUMN "blood_group" TYPE "blood_group" USING "blood_group"::"blood_group";
ALTER TABLE "allergies" ALTER COLUMN "severity" TYPE "allergy_severity" USING "severity"::"allergy_severity";
ALTER TABLE "chronic_conditions" ALTER COLUMN "status" TYPE "chronic_condition_status" USING "status"::"chronic_condition_status";
ALTER TABLE "medical_records" ALTER COLUMN "type" TYPE "medical_record_type" USING "type"::"medical_record_type";
ALTER TABLE "medical_records" ALTER COLUMN "privacy" TYPE "medical_record_privacy" USING "privacy"::"medical_record_privacy";
ALTER TABLE "reminders" ALTER COLUMN "type" TYPE "reminder_type" USING "type"::"reminder_type";
ALTER TABLE "reminders" ALTER COLUMN "frequency" TYPE "reminder_frequency" USING "frequency"::"reminder_frequency";
ALTER TABLE "reminders" ALTER COLUMN "status" TYPE "reminder_status" USING "status"::"reminder_status";
ALTER TABLE "share_tokens" ALTER COLUMN "access_scope" TYPE "share_token_scope"[] USING "access_scope"::"share_token_scope"[];
ALTER TABLE "share_tokens" ALTER COLUMN "status" TYPE "share_token_status" USING "status"::"share_token_status";
ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "audit_log_action" USING "action"::"audit_log_action";
ALTER TABLE "audit_logs" ALTER COLUMN "status" TYPE "audit_log_status" USING "status"::"audit_log_status";
ALTER TABLE "emergency_sos" ALTER COLUMN "status" TYPE "emergency_sos_status" USING "status"::"emergency_sos_status";
ALTER TABLE "emergency_contacts" ALTER COLUMN "relationship" TYPE "emergency_contact_relationship" USING "relationship"::"emergency_contact_relationship";